name: Model Retraining CI

on:
  push:
    paths:
      - MLProject/**
      - .github/workflows/ci.yml
  workflow_dispatch:  # untuk retraining manual

jobs:
  retrain-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: energy_model_env
          environment-file: MLProject/conda.yaml
          python-version: 3.12

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run .
