name: CI MLflow Docker Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.7

    - name: Check Env
      run: |
        echo "Python version: $(python --version)"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r MLProject/requirements.txt || true

    - name: Run mlflow project
      working-directory: ./MLProject
      run: |
        mlflow run .

    - name: Get latest MLflow run_id
      id: get_run
      run: |
        echo "RUN_ID=$(mlflow experiments list --view-type ACTIVE | tail -n 1 | awk '{print $1}')" >> $GITHUB_ENV

    - name: Install Python dependencies
      run: |
        pip install -r MLProject/requirements.txt || true

    - name: Commit artifacts to repo
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add artifacts/
        git commit -m "Add latest model artifacts"
        git push
        echo "Artifacts committed to the repository."

    # - name: Build Docker Model
    #   run: |
    #     docker build -t mlflow-docker-model .

    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Tag Docker Image
    #   run: |
    #     docker tag mlflow-docker-model ${{ secrets.DOCKER_USERNAME }}/mlflow-docker-model:latest

    # - name: Push Docker Image
    #   run: |
    #     docker push ${{ secrets.DOCKER_USERNAME }}/mlflow-docker-model:latest
